server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///Users/joheiss/dev/tutorials/java/spring/spring6-microservices/config"

        git:
          uri: https://github.com/joheiss/spring6-microservices-banking-configvalues.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
          show-details: always
          probes:
              enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "IIEpAIBAAKCAQEAwOsN8Wiq4g7J3dQ8U4NlW+Tuz"

logging:
  level:
    com:
      jovisco: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
    