server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///Users/joheiss/dev/tutorials/java/spring/spring6-microservices/config"

        git:
          uri: https://github.com/joheiss/spring6-microservices-banking-configvalues.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          